config/routes.rb
Rails.application.routes.draw do
  resources :vacation_homes do
    collection { post :import }
  end

  get 'search', to: 'vacation_homes#search'

  get 'homes', to: 'vacation_homes#index'

  root to: 'vacation_homes#search'

end

app/models/vacation_home.rb
class VacationHome < ActiveRecord::Base
  require 'csv'

# Method for searching the VHR database
# TO DO - Implement better searh mechanism like elasticsearch
  def self.search(search)
    where("property_address LIKE :search OR contact_name LIKE :search OR contact_email LIKE :search OR contact_phone LIKE :search", search: "%#{search}%")
  end

# Method for importing VHR csv files into our database
  def self.import(file)
    # Future to do: add a header check to ensure that our headers in the csv import are what we expect so we don't blow up our data
    CSV.foreach(file.path, headers: true) do |row|
      vacation_home = find_or_initialize_by(business_id: row['business_id']) # (knowledge nugget for matt: biz_id refs our db then row:biz_id refs our csv file)
      vacation_home.attributes =  {
        business_id: row['business_id'],
        business_name: row['business_name'],
        property_address: row['property_address'],
        max_occupancy: row['max_occupancy'],
        parking_spaces: row['parking_spaces'],
        refuse_day: row['refuse_day'],
        contact_name: row['contact_name'],
        contact_email: row['contact_email'],
        contact_phone: row['contact_phone']
      }
      vacation_home.save!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/vacation_homes_controller.rb
class VacationHomesController < ApplicationController
  before_action :set_vacation_home, only: [:show, :edit, :update, :destroy]

  # GET /vacation_homes
  # GET /vacation_homes.json
  def index
    @vacation_homes = VacationHome.all
    if params[:search]
      @vacation_homes = VacationHome.search(params[:search])
      if @vacation_homes.any?
        redirect_to '/search'
        flash[:success] = "We have a match for #{params[:search]}"
      else
        redirect_to '/search'
        flash[:danger] = "#{params[:search]} doesn't match up"
      end
    else
      @vacation_homes = VacationHome.all.order("property_address")
    end
  end

  # GET /vacation_homes/1
  # GET /vacation_homes/1.json
  def show
  end

  # GET /vacation_homes/new
  def new
    @vacation_home = VacationHome.new
  end

  # GET /vacation_homes/1/edit
  def edit
  end

  # POST /vacation_homes
  # POST /vacation_homes.json
  def create
    @vacation_home = VacationHome.new(vacation_home_params)

    respond_to do |format|
      if @vacation_home.save
        format.html { redirect_to @vacation_home, notice: 'Vacation home was successfully created.' }
        format.json { render :show, status: :created, location: @vacation_home }
      else
        format.html { render :new }
        format.json { render json: @vacation_home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacation_homes/1
  # PATCH/PUT /vacation_homes/1.json
  def update
    respond_to do |format|
      if @vacation_home.update(vacation_home_params)
        format.html { redirect_to @vacation_home, notice: 'Vacation home was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacation_home }
      else
        format.html { render :edit }
        format.json { render json: @vacation_home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacation_homes/1
  # DELETE /vacation_homes/1.json
  def destroy
    @vacation_home.destroy
    respond_to do |format|
      format.html { redirect_to vacation_homes_url, notice: 'Vacation home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    VacationHome.import(params[:file])
    redirect_to vacation_homes_url, notice: "VHRs Database Updated"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacation_home
      @vacation_home = VacationHome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacation_home_params
      params.require(:vacation_home).permit(:business_id, :business_name, :contact_name, :contact_email, :contact_phone, :property_address, :max_occupancy, :parking_spaces, :refuse_day)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vacation_homes_helper.rb
module VacationHomesHelper
end

app/views/layouts/_alerts.html.erb
<div class='row'>
  <div class='col-xs-10'>
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href='#' class='close' data-dismiss='alert'>&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VhrValidator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vacation_homes/_form.html.erb
<%= form_for(@vacation_home) do |f| %>
  <% if @vacation_home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vacation_home.errors.count, "error") %> prohibited this vacation_home from being saved:</h2>

      <ul>
      <% @vacation_home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :business_id %><br>
    <%= f.text_field :business_id %>
  </div>
  <div class="field">
    <%= f.label :business_name %><br>
    <%= f.text_field :business_name %>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br>
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br>
    <%= f.text_field :contact_email %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br>
    <%= f.text_field :contact_phone %>
  </div>
  <div class="field">
    <%= f.label :property_address %><br>
    <%= f.text_field :property_address %>
  </div>
  <div class="field">
    <%= f.label :max_occupancy %><br>
    <%= f.number_field :max_occupancy %>
  </div>
  <div class="field">
    <%= f.label :parking_spaces %><br>
    <%= f.number_field :parking_spaces %>
  </div>
  <div class="field">
    <%= f.label :refuse_day %><br>
    <%= f.text_field :refuse_day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vacation_homes/edit.html.erb
<h1>Editing Vacation Home</h1>

<%= render 'form' %>

<%= link_to 'Show', @vacation_home %> |
<%= link_to 'Back', vacation_homes_path %>

app/views/vacation_homes/index.html.erb
<div class="index_page"
  <p id="notice"><%= notice %></p>

  <h1>Listing Vacation Homes</h1>

  <table>
    <thead>
      <tr>
        <th>Business ID</th>
        <th>Business Name</th>
        <th>Contact Name</th>
        <th>Contact Email</th>
        <th>Contact Phone</th>
        <th>Property Address</th>
        <th>Max Occupancy</th>
        <th>Parking Spaces</th>
        <th>Refuse Day</th>
        </th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @vacation_homes.each do |vacation_home| %>
        <tr>
          <td><%= vacation_home.business_id %></td>
          <td><%= vacation_home.business_name %></td>
          <td><%= vacation_home.contact_name %></td>
          <td><%= vacation_home.contact_email %></td>
          <td><%= vacation_home.contact_phone %></td>
          <td><%= vacation_home.property_address %></td>
          <td><%= vacation_home.max_occupancy %></td>
          <td><%= vacation_home.parking_spaces %></td>
          <td><%= vacation_home.refuse_day %></td>
          <td><%= link_to 'Show', vacation_home %></td>
          <td><%= link_to 'Edit', edit_vacation_home_path(vacation_home) %></td>
          <td><%= link_to 'Destroy', vacation_home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <!-- <%= link_to 'New Vacation home', new_vacation_home_path %> -->
  <br />
  <br />
  <%= form_tag import_vacation_homes_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
  <% end %>
</div>

app/views/vacation_homes/new.html.erb
<h1>New Vacation Home</h1>

<%= render 'form' %>

<%= link_to 'Back', vacation_homes_path %>

app/views/vacation_homes/search.html.erb
<div class="container">
  <div class="jumbotron" id="jumbotron_search" align="center">
    <h1>South Lake Tahoe<br>Vacation Home Rental Validator</h1>
    <h3>Renting a vacation home in South Lake Tahoe? Make sure you don't get scammed!</h3>
    <p>Before you rent, search the Vacation Home Rental database for the property address or contact information of the person you're communicating with to make sure it's either the homeowner or rental manager.</p>
    <div class="row" id="home_search">
      <div class="col-md-8 col-md-offset-2 panel panel-default">
        <div class="panel-body">
          <%= form_tag(vacation_homes_path, :method => "GET", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], class: "search_field", placeholder: "Property address or contact info of the person you're communicating with" %>
            <%= submit_tag "Search", class: "btn btn-primary btn-lrg search_btn", :name => nil %>
          <% end %>
          <%= render 'layouts/alerts' %>
          <!--TO DO - implement messaging for matching of info instead of going to a page with the search result -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/vacation_homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Business:</strong>
  <%= @vacation_home.business_id %>
</p>

<p>
  <strong>Business name:</strong>
  <%= @vacation_home.business_name %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @vacation_home.contact_name %>
</p>

<p>
  <strong>Contact email:</strong>
  <%= @vacation_home.contact_email %>
</p>

<p>
  <strong>Contact phone:</strong>
  <%= @vacation_home.contact_phone %>
</p>

<p>
  <strong>Property address:</strong>
  <%= @vacation_home.property_address %>
</p>

<p>
  <strong>Max occupancy:</strong>
  <%= @vacation_home.max_occupancy %>
</p>

<p>
  <strong>Parking spaces:</strong>
  <%= @vacation_home.parking_spaces %>
</p>

<p>
  <strong>Refuse day:</strong>
  <%= @vacation_home.refuse_day %>
</p>

<%= link_to 'Edit', edit_vacation_home_path(@vacation_home) %> |
<%= link_to 'Back', vacation_homes_path %>